### PR TITLE
fix(@vtmn/svelte, @vtmn/vue, @vtmn/react): interactive `VtmnRating` have duplicate `$$restProps`

### LINKED ISSUE #1385: bug(@vtmn/svelte): component `VtmnRating` call many times `$$restProps` on child
image

There is an issue on the restProps part, here, if the user apply a class on the `VtmnRating` component, this one will be applied on the main node and the first child (only if it is not readonly).

We have to defined where the data must be applied. And if the second div should apply the restProps.

### PR DESCRIPTION
**Pull request by Tlahey**
Closes #1385 

## Changes description
Add on the `VtmnRating` svelte component a check on the restProps in order to not apply it on the root level of the component and under if the rating is interactive.
No changes on the class, only on props like aria-label etc ...

## Context
In some case, if the component is interactive, the class are applied twice, on the root level and under.

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [x] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [x] Check your code additions will fail neither code linting checks.
- [x] I have reviewed the submitted code.
- [x] I have tested on related showcases.
- [x] If it includes design changes, please ask for a review `design-system-core-team-design` GitHub team.

## Does this introduce a breaking change?

- No

Tested on svelte / react / vue on storybook.

### CODE REVIEW

**Review by lauthieb — APPROVED** [review]

**Comment by lauthieb** [comment]
Thanks @Tlahey, that's ok for me. I'll let @thibault-mahe review next Tuesday.

File: packages/sources/react/src/components/indicators/VtmnRating/VtmnRating.tsx [hunk 1]
```diff
@@ -105,7 +105,7 @@ export const VtmnRating = ({
         className,
       )}
       aria-disabled={disabled}
-      {...props}
+      {...(readonly && props)}
```
Comment (thibault-mahe) [inline packages/sources/react/src/components/indicators/VtmnRating/VtmnRating.tsx:108]: 2 questions:
- it is not clear to me why there is a condition on the readonly props?
- no tested but does this work? Since you are spreading, shouldn't you use a ternary here like `{...(readonly ? props : {})}` ?

File: packages/sources/svelte/src/components/indicators/VtmnRating/VtmnRating.svelte [hunk 2]
```diff
@@ -72,7 +72,11 @@
   $: starsCnt = compact && readonly ? 1 : 5;
 </script>
 
-<div class={componentClass} aria-disabled={disabled} {...$$restProps}>
+<div
+  class={componentClass}
+  aria-disabled={disabled}
+  {...readonly && $$restProps}
```
Comment (thibault-mahe) [inline packages/sources/svelte/src/components/indicators/VtmnRating/VtmnRating.svelte:78]: same issue here + should you add parentheses here?

File: packages/sources/svelte/src/components/indicators/VtmnRating/test/VtmnRating.spec.js [hunk 3]
```diff
@@ -354,6 +354,16 @@ describe('VtmnRating', () => {
       expect(inputs[1].checked).toEqual(true);
       expect(getInteractive(container)).toHaveAttribute('data-rating', '2');
     });
+
+    test('Should not contains restProps many times', () => {
```
Comment (thibault-mahe) [inline packages/sources/svelte/src/components/indicators/VtmnRating/test/VtmnRating.spec.js:358]: `Should not have repeated restProps`

File: packages/sources/react/src/components/indicators/VtmnRating/VtmnRating.tsx (hunk 1 above)
Comment (Tlahey) [reply packages/sources/react/src/components/indicators/VtmnRating/VtmnRating.tsx:108]: For the ternary, it is not necesary, 
image

The condition is on the readonly part because, if we are on readonly true / false, the structure are not the same. 

image

With readonly false, we have a sub level with `vtmn-rating--interactive` which is contains all properties like aria-labels etc ... who the user can override with the restProps. 

This level doesn't exist if readonly is true.
image

File: packages/sources/svelte/src/components/indicators/VtmnRating/VtmnRating.svelte (hunk 2 above)
Comment (Tlahey) [reply packages/sources/svelte/src/components/indicators/VtmnRating/VtmnRating.svelte:78]: yes indeed

**Review by lauthieb — APPROVED** [review]

File: packages/sources/react/src/components/indicators/VtmnRating/VtmnRating.tsx (hunk 1 above)
Comment (lauthieb) [reply packages/sources/react/src/components/indicators/VtmnRating/VtmnRating.tsx:108]: Thanks @Tlahey for this explanation.
Since @thibault-mahe is on vacation this week and is replacing him during his absence, this PR is open and your explanations seem to be correct. I will therefore take the decision to merge this PR. 
@thibault-mahe, don't hesitate to come back to it if you need to make a modification to these changes via a patch when you come back. 
Thanks!
