### PR TITLE
fix(@vtmn/react): TS compilation error 

### LINKED ISSUE #650: bug(@vtmn/react): Typescript warnings in the console when `yarn build`
# Bug Report

Hello,
There are Typescript warnings in the console when `yarn build` on `@vtmn/react` package.

Capture d’écran 2021-10-04 à 12 37 14

**Steps to reproduce**

`yarn && cd packages/sources/react && yarn build`

Thanks!

### PR DESCRIPTION
**Pull request by blemoine**
## Pull Request checklist

🚨 Please review the [guidelines for contributing](../blob/main/CONTRIBUTING.md) to this repository.

- [X] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Don't request your main!
- [X] Check the commit's or even all commits' message styles matches our requested structure.
- [X]  Check your code additions will fail neither code linting checks nor unit test.
- [X] Check PR name, it must follow the https://www.conventionalcommits.org pattern
- [x] If it's a new component in CSS, ask for design review

## Description

Fix compilation error for React components ; 

* React.memo doesn't support components returning an array,
  hence rollbacking to fragment syntax.
* `input`s and `textarea`s don't have the same valid HTML attributes.
   As the component uses `multiline` to know when to render one or the other,
   I explicited in the type that if `multiline` is true,
   then the expected attributes are of textarea,
   and that if `multiline` is false, the expected attributes are of input.
* VtmnToggle overrides `size` with its own semantic, 
   it implies that VtmnToggleProps doesn't fully extends HTMLInputProps

Closes #650 

## Does this introduce a breaking change?

- Yes

User of VtmnTextInput  using `multiline=true` and explicitly writing a callback expecting a HTMLInputElement may have to change the type to HTMLTextareaElement.  While this is a "breaking change" for the user - as they have to change their code - it's really a fix, because they were really receiving a HTMLTextareaElement, it was jsut badly typed. 

## Other information

Just a piece of opinion: I suggest to transform TS warns to TS errors (preventing the merge). Of the 3 problems above, at least 2 were real problems that could lead to users bugs.  (I'm not 100% sure about `React.memo`, if the problem really lies with `memo` Or with the type declaration from facebook)

❤️ Thank you!

### CODE REVIEW

**Review by GaspardMathon — APPROVED** [review]

File: packages/sources/react/src/components/VtmnTextInput/VtmnTextInput.tsx [hunk 1]
```diff
@@ -69,56 +79,58 @@ export const VtmnTextInput = ({
   icon = undefined,
   identifier,
   labelText,
-  multiline = false,
+
```
Comment (lauthieb) [inline packages/sources/react/src/components/VtmnTextInput/VtmnTextInput.tsx:82]:
```suggestion
```

**Review by lauthieb — APPROVED** [review]

**Comment by lauthieb** [comment]
Thank you very much @blemoine for these fixes and their explanations. Really appreciated. ❤️
