### PR TITLE
fix(@vtmn/react): support style prop for `VtmnDropdown` component

### LINKED ISSUE #1400: bug(@vtmn/react): `VtmnDropdown` doesn't support `style` property in jsx/tsx files
**Describe the bug**
When I set style property to VtmnDropdown component, it's not supported and I need to create a simple css file to momentarily 
resolve the issue
Screenshot from 2023-03-24 12-04-53
Screenshot from 2023-03-24 12-04-40

**Steps to reproduce**
- Install React
- Install the Vtmn package for React

**Expected behavior**
When I create a style property for VtmnDropdown component, it should be supported

**Version affected**
@react: 18.2.0
@vtmn/react: 0.67.0

### PR DESCRIPTION
**Pull request by lauthieb**
## Changes description

Closes #1400 (thanks @jdeca-decat for reporting this)

## Context

For your information and to avoid breaking changes for people that already uses `VtmnDropdown`, I didn't spread all the `props` object. I preferred to only pass through the `style` prop.

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [x] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [x] Check your code additions will fail neither code linting checks.
- [x] I have reviewed the submitted code.
- [x] I have tested on related showcases.
- [x] If it includes design changes, please ask for a review `design-system-core-team-design` GitHub team.

## Does this introduce a breaking change?

- No

### CODE REVIEW

File: packages/sources/react/src/components/actions/VtmnDropdown/VtmnDropdown.tsx [hunk 1]
```diff
@@ -41,12 +41,17 @@ export const VtmnDropdown = ({
   summary = 'Dropdown',
   disabled = false,
   className,
```
Comment (lauthieb) [inline packages/sources/react/src/components/actions/VtmnDropdown/VtmnDropdown.tsx:43]:
```suggestion
  className = '',
```

**Review by thibault-mahe — APPROVED** [review]
